# 扫描全能王 解锁黄金会员 (CamScanner Unlock Quantumult X 配置)

[rewrite_local]
^https:\/\/.*\.(intsig\.net|camscanner\.com) url script-response-body https://raw.githubusercontent.com/chxm1023/Rewrite/main/CamScanner.js

[mitm]
hostname = *.camscanner.com, *.intsig.net
